// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBo6EzOgOoogled5AJ4tb67Y2ZmgOhg9_4',
    appId: '1:299746917015:web:734d1f53cfbf89f7b447d2',
    messagingSenderId: '299746917015',
    projectId: 'personal-virtual-encourager',
    authDomain: 'personal-virtual-encourager.firebaseapp.com',
    storageBucket: 'personal-virtual-encourager.firebasestorage.app',
    measurementId: 'G-BV3TGD23FL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB014HUug9wdeLyARJTdg9PqfDtIODSWnI',
    appId: '1:629387082368:android:8173d29bebd74b3bec8465',
    messagingSenderId: '629387082368',
    projectId: 'peacepulsecotest',
    databaseURL: 'https://peacepulsecotest-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'peacepulsecotest.appspot.com',
  );

}